# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1c4f51991b269b3727df871e64a1b020a745453ff007e00d4686b8042f46a9651b49379a4e967f30d993d2a63c1425c4460a143b4e79cfa7a781a6bae804d34

test:
  secret_key_base: 232094fb47ae5c888f24f6ddc65d4408971dc0b47e446baee87d64f4baf595b13ac7ebfa835e57db55d2202bfeda4b83873e2607882e43184c236be85b6ebb4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
